shiosyakeyakini-info/misskey_dart

- lib/src/data/meta_response.dart
- lib/src/data/meta_response.freezed.dart
- lib/src/data/meta_response.g.dart
metaのレスポンスのnameは初期状態ではnullなので修正します
https://github.com/misskey-dev/misskey/blob/13.12.2/packages/backend/src/models/entities/Meta.ts#L14-L17
> MetaResponseを修正

- lib/src/data/users/users_show_response.dart
- lib/src/data/users/users_show_response.freezed.dart
- lib/src/data/users/users_show_response.g.dart
UsersShowResponse のフィールドのうち、ログイン時のみ返されるものを追加しました
> UsersShowResponse のフィールドを追加

- lib/src/data/base/follow_request.dart
- lib/src/data/base/follow_request.freezed.dart
- lib/src/data/base/follow_request.g.dart
- test/misskey_dart_test.dart
follower/followee のところが followerId/followeeId になっていたのを直しました
テストで `following.requests.list()` を呼んだ後に `toList()` をしないとIterableのままで中身の `fromJson()` が呼ばれないようなので、テストも修正しました
> FollowRequest を修正

- lib/misskey_dart.dart
- test/misskey_dart_test.dart
src/enums 以下の enum のうち、リクエストやレスポンスに含まれているためライブラリ外からも使用することになるものをエクスポートしました
> enumをエクスポート

- lib/src/data/streaming/streaming_request.dart
- lib/src/data/streaming/streaming_request.freezed.dart
- lib/src/misskey_channels.dart
- lib/src/misskey_dart_base.dart
- lib/src/services/api_service.dart
- lib/src/services/socket_controller.dart
- lib/src/services/streaming_service.dart
- test/misskey_dart_test.dart
ストリームを共有し、それぞれのチャンネルへのメッセージを振り分けるようにしました
- StreamingService でチャンネルとidの対応を保持します
- 切断済みのidのメッセージが来たとき、そのidのチャンネルを切断します
- https://github.com/shiosyakeyakini-info/miria/issues/13#issuecomment-1657066979
> WebSocketChannelを共有する

- lib/src/services/socket_controller.dart
reconnectをしたときにisDisconnectedのままになっていたのを修正しました
> fix reconnect

- .gitignore
- lib/misskey_dart.dart
- lib/src/data/roles/roles_notes_request.dart
- lib/src/data/roles/roles_notes_request.freezed.dart
- lib/src/data/roles/roles_notes_request.g.dart
- lib/src/data/roles/roles_show_request.dart
- lib/src/data/roles/roles_show_request.freezed.dart
- lib/src/data/roles/roles_show_request.g.dart
- lib/src/data/streaming/streaming_request.g.dart
- lib/src/enums/channel.dart
- lib/src/misskey_dart_base.dart
- lib/src/misskey_note.dart
- lib/src/misskey_roles.dart
以下のエンドポイントに対応したAPIを追加しました
- roles/notes
- roles/show
以下のストリーミングチャンネルに対応したAPIを追加しました
- roleTimeline
> ロール関連のAPIを追加

- lib/src/data/users/users_show_response.dart
UsersShowResponse.toUserでnameが抜けていたのを修正しました
> UsersShowResponse.toUserでnameを渡す

- lib/src/data/base/community_channel.dart
- lib/src/data/base/community_channel.freezed.dart
- lib/src/data/base/community_channel.g.dart
CommunityChannel の非ログイン時に返されないフィールドを nullable にしました
Related to https://github.com/shiosyakeyakini-info/miria/issues/139
> 非ログイン時にチャンネルを取得できるように

- lib/src/data/base/note.dart
- lib/src/data/base/note.freezed.dart
- lib/src/data/base/note.g.dart
- lib/src/data/base/user.dart
- lib/src/data/base/user.freezed.dart
- lib/src/data/base/user.g.dart
- lib/src/data/emoji_response.dart
- lib/src/data/emoji_response.freezed.dart
- lib/src/data/emoji_response.g.dart
`@Default()` の後に型を書くべきところを忘れていて `dynamic` になっていたものを修正しました
> `@Default()` の後の型が抜けていたのを修正

- lib/src/data/clips/clips_notes_request.dart
- lib/src/data/clips/clips_notes_request.freezed.dart
- lib/src/data/clips/clips_notes_request.g.dart
https://github.com/misskey-dev/misskey/blob/2023.10.1/packages/backend/src/server/api/endpoints/clips/notes.ts#L40-L49
> ClipsNotesRequestのclipIdをnon-nullableに

- lib/src/misskey_dart_base.dart
> antennaStreamのonVotedを修正

- lib/src/data/base/clip.dart
- lib/src/data/base/clip.freezed.dart
- lib/src/data/base/clip.g.dart
非ログイン時にクリップの取得ができなかったので修正しました
https://github.com/misskey-dev/misskey/blob/30594dde181e9d151542c41c6f09e673fcbb3124/packages/backend/src/core/entities/ClipEntityService.ts#L49
> ClipのisFavoritedをnullableに

- lib/src/data/emoji_response.dart
- lib/src/data/emoji_response.freezed.dart
- lib/src/data/emoji_response.g.dart
- lib/src/data/emojis_response.dart
- lib/src/data/emojis_response.freezed.dart
- lib/src/data/emojis_response.g.dart
`emojis` と `emoji` の返り値に `roleIdsThatCanBeUsedThisEmojiAsReaction` を追加しました
> roleIdsThatCanBeUsedThisEmojiAsReactionを追加

- lib/misskey_dart.dart
- lib/src/data/users/users_search_by_username_and_host_request.dart
- lib/src/data/users/users_search_by_username_and_host_request.freezed.dart
- lib/src/data/users/users_search_by_username_and_host_request.g.dart
- lib/src/misskey_users.dart
- test/misskey_users_test.dart
`users/search-by-username-and-host` に対応するメソッドを追加しました
> search-by-username-and-hostを追加

- lib/src/data/base/user.dart
- lib/src/data/base/user.freezed.dart
- lib/src/data/base/user.g.dart
- lib/src/data/i/i_update_request.dart
- lib/src/data/i/i_update_request.freezed.dart
- lib/src/data/i/i_update_request.g.dart
- `UserDetailedNotMeWithRelations` と `MeDetailed` に `followedMessage` を追加しました
- `IUpdateRequest` に `followedMessage` を追加しました
ref: `https://github.com/misskey-dev/misskey/pull/14430`
> フォローされた際のメッセージを追加

- lib/src/data/i/i_notifications_request.g.dart
- lib/src/data/i/i_notifications_response.dart
- lib/src/data/i/i_notifications_response.freezed.dart
- lib/src/data/i/i_notifications_response.g.dart
- lib/src/enums/notification_type.dart
以下の通知に関する変更に対応しました
- `https://github.com/misskey-dev/misskey/pull/14484`
- `https://github.com/misskey-dev/misskey/pull/14430`
- `https://github.com/misskey-dev/misskey/pull/14673`
> Misskey 2024.10.0で追加される通知に対応

- lib/src/data/base/page.dart
- lib/src/data/base/page.freezed.dart
- lib/src/data/base/page.g.dart
以下のフィールドをnullableにしました
- `PageText.text`
- `PageImage.fileId`
- `PageNote.note`
> PageContentのフィールドをnullableに

- lib/src/data/i/i_update_request.dart
- lib/src/data/i/i_update_request.freezed.dart
- lib/src/data/i/i_update_request.g.dart
`IUpdateRequest` で `birthday` の型が指定されていなかったのを修正しました
> IUpdateRequestの抜けていた型を追加

- lib/src/data/antennas/antennas_create_request.dart
- lib/src/data/antennas/antennas_create_request.freezed.dart
- lib/src/data/antennas/antennas_create_request.g.dart
- lib/src/data/antennas/antennas_update_request.dart
- lib/src/data/antennas/antennas_update_request.freezed.dart
- lib/src/data/antennas/antennas_update_request.g.dart
- lib/src/data/base/antenna.dart
- lib/src/data/base/antenna.freezed.dart
- lib/src/data/base/antenna.g.dart
`https://github.com/misskey-dev/misskey/pull/13603` に対応しました
> アンテナにexcludeBotsを追加

- lib/src/data/base/user.dart
- lib/src/data/base/user.freezed.dart
- lib/src/data/base/user.g.dart
- lib/src/data/chat/chat_joinning.dart
- lib/src/data/chat/chat_joinning.freezed.dart
- lib/src/data/chat/chat_joinning.g.dart
- lib/src/data/chat/chat_message.dart
- lib/src/data/chat/chat_message.freezed.dart
- lib/src/data/chat/chat_message.g.dart
- lib/src/data/chat/chat_rooms_create_request.dart
- lib/src/data/chat/chat_rooms_create_request.freezed.dart
- lib/src/data/chat/chat_rooms_create_request.g.dart
- lib/src/data/i/i_update_request.dart
- lib/src/data/i/i_update_request.freezed.dart
- lib/src/data/i/i_update_request.g.dart
- lib/src/misskey_chat.dart
- test/misskey_chat_test.dart
チャットのテストを追加しました
また、テストを書くために `IUpdateRequest` を更新し、関連するユーザーの型も更新しました
テストが通るようにするために行った修正を含んでいます
Docker Hubでのlatestが2025.3.1なので落ちていますが、developで動かせば通ります
https://github.com/poppingmoon/misskey_dart/actions/runs/14207554306/job/39808463166
> チャットのテストを追加

- lib/src/data/base/user.dart
- lib/src/data/base/user.freezed.dart
- lib/src/data/base/user.g.dart
- lib/src/data/chat/chat_message.dart
- lib/src/data/chat/chat_message.freezed.dart
- lib/src/data/chat/chat_message.g.dart
- lib/src/data/chat/chat_rooms_create_request.dart
- lib/src/data/chat/chat_rooms_create_request.freezed.dart
- lib/src/data/chat/chat_rooms_create_request.g.dart
- lib/src/data/i/i_update_request.dart
- lib/src/data/i/i_update_request.freezed.dart
- lib/src/data/i/i_update_request.g.dart
- lib/src/data/streaming/streaming_response.dart
- lib/src/data/streaming/streaming_response.freezed.dart
- lib/src/data/streaming/streaming_response.g.dart
- lib/src/data/streaming/streaming_response_sub_type.dart
- lib/src/data/streaming/streaming_response_sub_type.freezed.dart
- lib/src/data/streaming/streaming_response_sub_type.g.dart
- lib/src/services/streaming_service.dart
- lib/src/services/streaming_service_impl.dart
- test/streaming_test.dart
- `message` 以外のチャットのイベントにも対応しました
- https://github.com/misskey-dev/misskey/blob/2025.4.0-beta.2/packages/backend/src/core/GlobalEventService.ts#L162-L175
- https://github.com/misskey-dev/misskey/blob/2025.4.0-beta.2/packages/backend/src/core/GlobalEventService.ts#L76
- チャットを既読にできるようにしました
- https://github.com/misskey-dev/misskey/blob/2025.4.0-beta.2/packages/backend/src/server/api/stream/channels/chat-user.ts#L45-L49
- https://github.com/misskey-dev/misskey/blob/2025.4.0-beta.2/packages/backend/src/server/api/stream/channels/chat-room.ts#L45-L49
- テストを追加しました
- https://github.com/poppingmoon/misskey_dart/actions/runs/14240172480/job/39908048172
> チャットのストリーミングに対応

- lib/src/data/antennas/antennas_create_request.dart
- lib/src/data/antennas/antennas_create_request.freezed.dart
- lib/src/data/antennas/antennas_create_request.g.dart
- lib/src/data/antennas/antennas_update_request.dart
- lib/src/data/antennas/antennas_update_request.freezed.dart
- lib/src/data/antennas/antennas_update_request.g.dart
- lib/src/data/base/antenna.dart
- lib/src/data/base/antenna.freezed.dart
- lib/src/data/base/antenna.g.dart
`Antenna`, `AntennasCreateRequest`, `AntennasUpdateRequest` に `excludeNotesInSensitiveChannel` を追加しました
ref: `https://github.com/misskey-dev/misskey/pull/15346`
> アンテナでセンシティブチャンネルを除外する設定に対応

- lib/src/data/base/user.dart
- lib/src/data/base/user.freezed.dart
- lib/src/data/base/user.g.dart
ref: https://github.com/misskey-dev/misskey/pull/15765/files#diff-6b07e8035a467caae8c51e1a2d9b217e97665ee1e01da00fb1540e76f566cf4d
> canChatをchatAvailabilityに変更

- test/misskey_chat_test.dart
chatScopeの更新をawaitしていなかったせいでチャットのテストが不安定になっていた問題を修正しました
> chatScopeの更新をsetUpで行う

- lib/src/data/streaming/streaming_request.dart
- lib/src/data/streaming/streaming_request.freezed.dart
- lib/src/data/streaming/streaming_request.g.dart
- lib/src/enums/channel.dart
- lib/src/enums/channel.freezed.dart
- lib/src/services/streaming_service_impl.dart
customを導入してカスタムエンドポイントをリクエストできるように修正
> Channelをsealed classに変更

- lib/src/services/streaming_service_impl.dart
- 接続失敗時のリトライに5秒の待ち時間を追加しました
　Wi-Fiが瞬断された場合などの再接続待ち時間として入れました
- 短期間(5秒以内)にonError/onDoneが繰り返し発生した場合、接続再試行待ち時間を少しずつ伸ばすように(最大5秒)
　サーバーが不安定になっていた場合などでの過負荷対策
- 稀にデッドロックして接続が行えなくなってしまうのを修正しました
> 接続・切断処理の修正と、再接続が短時間に発生した場合に待ち時間の追加
